### PR TITLE
Move log file to more of a temporary location

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Comment by stkw0** [comment]
oh nice, I was making something similar but was thinking if it was better to use the time on the log name or do something like ebuildtester_sys_libs_glibc, but the latter was more difficult to implement.

**Comment by nicolasbock** [comment]
Please have another look @stkw0 . If you like this change please go ahead and `approve` it. Thanks!

**Comment by stkw0** [comment]
Looks awesome, thank you!

**Review by stkw0 — APPROVED** [review]

**Comment by nicolasbock** [comment]
Thanks for the review!

**Pull request merged**
