### PR TITLE
Add ccache support

### PR DESCRIPTION
**Pull request by stkw0**
Closes: #163

### CODE REVIEW

**Review by nicolasbock — CHANGES_REQUESTED** [review]
This looks great @stkw0 ! 

Just one comment: Don't you have to also emerge `ccache` in the container to be able to use this feature?

**Comment by stkw0** [comment]
> This looks great @stkw0 !
> 
> Just one comment: Don't you have to also emerge `ccache` in the container to be able to use this feature?

Yes, I forgot it, I still didn't had time to test it with properly. Also I may add support for CCACHE_SIZE although I am not sure how this will work in a shared CCACHE

**Comment by stkw0** [comment]
I used the default value for CCACHE_DIR according to man make.conf. I will
check which is the real default value when I get home

**Comment by nicolasbock** [comment]
Ah ok, that makes sense. Thanks!

**Comment by stkw0** [comment]
Now it's working. Instead of adding another use flag for CCACHE_SIZE I created the configuration file for ccache which in my opinion is better as you don't have to remember to pass any extra flag and it applies everywhere

**Review by nicolasbock — APPROVED** [review]
Thanks @stkw0 !

**Pull request merged**
