### PR TITLE
Move away from deprecated pkg_resources

### PR DESCRIPTION
**Pull request by parona-source**
* Use importlib.metadata which has been included in the python standard library since 3.8.

### CODE REVIEW

**Comment by parona-source** [comment]
This is not urgent, there is no ETA on any sort of removal. Just one less deprecation warning.

**Comment by parona-source** [comment]
Surprised that 3.7 is still in the CI. https://devguide.python.org/versions/ eol'd a couple months ago and not supported ubuntu version defaults to it either (focal 3.8).

3.7 CI could be fixed by using the importlib_metadata backport.

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Thanks! I think we can safely remove the Python 3.7 tests from the GitHub workflows. Could you add the necessary changes to this PR? Thanks!

**Comment by parona-source** [comment]
Added 3.11 and 3.12 at while at it.

**Review by nicolasbock — APPROVED** [review]
Thanks!

**Comment by parona-source** [comment]
```
WARNING: html_static_path entry '_static' does not exist
/home/runner/work/ebuildtester/ebuildtester/docs/index.rst:1: WARNING: toctree contains reference to nonexisting document 'README'
checking consistency... /home/runner/work/ebuildtester/ebuildtester/docs/modules.rst: WARNING: document isn't included in any toctree
...
build finished with problems, 3 warnings.
ERROR: InvocationError for command /home/runner/work/ebuildtester/ebuildtester/.tox/docs/bin/sphinx-build -M linkcheck docs docs/_build (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
Error: Process completed with exit code 1.
```

**Comment by parona-source** [comment]
https://github.com/nicolasbock/ebuildtester/pull/214

**Pull request merged**
